In [ ]:
import numpy as np

# single dimension array
ary = np.array([1,2,3,4])
print(ary)

[1 2 3 4]


In [2]:
ary.shape

(4,)

In [ ]:

ary.reshape(1,4)   # 1 row and 4 columns

array([[1, 2, 3, 4]])

In [ ]:
# 2d array...
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [12]:
# Functions...

np.arange(0,10, 2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3,4))
# np.ones([2,3])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
## Numpy Vectorization operation..

arr = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(f"Addition:  {arr+ arr2}")

Addition:  [11 22 33 44 55]


In [25]:
print("Subtration: ", arr2-arr)

Subtration:  [ 9 18 27 36 45]


In [26]:
print("MUltiplication: ",arr2*arr)

MUltiplication:  [ 10  40  90 160 250]


In [27]:
print("Division  ", arr2/arr)

Division   [10. 10. 10. 10. 10.]


In [ ]:
## Universal functions..

res = np.sqrt(arr2)
print(res)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [31]:
### Array slicing and indexing....

arr_1 = np.array([[1,2,3,4], [44,33,22,11], [121,232,343,454]])
print("Array: \n", arr_1)

Array: 
 [[  1   2   3   4]
 [ 44  33  22  11]
 [121 232 343 454]]


In [34]:
arr_1[0][0]

np.int64(1)

In [35]:
## slicing...

arr_1[1:, 2:]

array([[ 22,  11],
       [343, 454]])

In [36]:
arr_1[:2, 2:]

array([[ 3,  4],
       [22, 11]])

In [37]:
arr_1[1:, 1:3]

array([[ 33,  22],
       [232, 343]])

In [40]:
arr_1[1:] = 80
print(arr_1)  ## all rows become 80 except 0

[[ 1  2  3  4]
 [80 80 80 80]
 [80 80 80 80]]


In [41]:
## Normalization.......

np_ar = np.array([1,2,3,4,5])

mean = np.mean(np_ar)
std_dev = np.std(np_ar)

normalization_data = (np_ar - mean)/std_dev

print(normalization_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [44]:
Arr = np.array([1,2,3,4,5,6,7,8, 9,10])
mean = np.mean(Arr)
print("mean: ", mean)

std_dev = np.std(Arr)
print("Standard  deviation: ", std_dev)

median = np.median(Arr)
print("Median == ",median )

variance = np.var(Arr)
print("Variance:  ", variance)

mean:  5.5
Standard  deviation:  2.8722813232690143
Median ==  5.5
Variance:   8.25


In [50]:
### Logical Operation...

tp = np.array([1,2,3,4,5,6,7,8,9])

print(tp[(tp>4) & (tp<9)])

[5 6 7 8]
